name: docu_diary
description: A new Flutter application
version: 1.0.15+18

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # wave: ^0.1.0
  flutter_localizations:
    sdk: flutter
  http: ^1.0.0
  pdf: ^3.10.4
  # flutter_statusbarcolor: ^0.2.3
  # autocomplete_textfield: ^1.7.3
  flutter_colorpicker: ^1.0.3
  # splashscreen: ^1.2.0
  auto_size_text: ^3.0.0
  dio: ^5.3.2
  flutter_typeahead: ^4.7.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  formz: ^0.6.1
  equatable: ^2.0.5
  sembast: ^3.5.0+1
  sembast_web: ">=1.2.0"
  synchronized: ^3.1.0
  path_provider: ^2.1.1
  intl: ^0.18.1
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.1
  datetime_picker_formfield_new: ^2.1.0
  date_format: ^2.0.7
  # dropdown_formfield: ^0.1.4
  rxdart: ^0.27.7
  url_launcher: ^6.1.14
  printing: ^5.11.0
  image_picker: ^1.0.4
  mime_type: ^1.0.0
  open_file: ^3.3.2
  package_info: ^2.0.2
  connectivity: ^3.0.6
  cached_network_image: ^3.2.3
  easy_debounce: ^2.0.3
  file_picker: ^5.5.0
  # network_state: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Cera-Medium
      fonts:
        - asset: assets/fonts/CERA-PRO-MEDIUM.ttf
    - family: Cera-Bold
      fonts:
        - asset: assets/fonts/CERA-PRO-BOLD.ttf
    - family: Cera-Light
      fonts:
        - asset: assets/fonts/CERA-PRO-LIGHT.ttf
