List<String> suggestions = [
  "Alt-Katholische Religionslehre",
  "Angewandte Informatik",
  "Biologie",
  "Biologisch-chemisches Praktikum",
  "Chemie",
  "Chinesisch",
  "Deutsch",
  "Englisch",
  "Erdkunde / Geographie",
  "Ethik",
  "Evangelische Religionslehre",
  "Französisch",
  "Geschichte",
  "Griechisch",
  "Heimat-und Sachkunde",
  "Informatik",
  "Italienisch",
  "Israelitische Religionslehre",
  "Japanisch",
  "Katholische Religionslehre",
  "Kunst",
  "Latein",
  "Lehrplanalternative Geologie",
  "Mathematik",
  "Moderne Fremdsprachen",
  "Musik",
  "Neugriechisch",
  "Orthodoxe Religionslehre",
  "Physik",
  "Polnisch",
  "Portugiesisch",
  "Russisch",
  "Sozialkunde",
  "Sozialpraktische Grundbildung",
  "Sozialwissenschaftliche Arbeitsfelder",
  "Spanisch",
  "Sport",
  "Theater und Film",
  "Tschechisch",
  "Türkisch",
  "Wirtschaft und Recht",
  "Wirtschaftsinformatik"
];
